/* eslint-disable */
export default [
  [
    "Props",
    "Type",
    "Required",
    "Default value",
    "Description",
    "Example",
  ],
  [
    "columns",
    "Array",
    "true",
    "",
    "Use this props to define table columns.",
    "['First name', 'Last name', 'Age']",
  ],
  [
    "rows",
    "Array",
    "true",
    "",
    "Use this props to define table rows.",
    "[ ['John', 'Doe', 23], ['Jane', 'Doe', 24] ]",
  ],
  [
    "rowKey",
    "String",
    "",
    "",
    "Define the field to be used as a key for each row.",
    "",
  ],
  [
    "rowHeight",
    "Number",
    "",
    "50",
    "Use this prop to set rows height (in px).",
    "",
  ],
  [
    "selectable",
    "Boolean",
    "",
    "false",
    "Use this props to make rows selectable.",
    "",
  ],
  [
    "paginated",
    "Boolean",
    "",
    "false",
    "Use this prop to have a paginated table",
    "",
  ],
  [
    "perPage",
    "Number",
    "",
    "10",
    "Use this prop to control the number of rows per page (when paginated)",
    "",
  ],
  [
    "placeholder",
    "String",
    "",
    "",
    "A text to display when the table is empty",
    "'Empty Table'",
  ],
  [
    "tableWidth",
    "String",
    "",
    "100%",
    "Use this prop to set table width.",
    "",
  ],
  [
    "tableLayout",
    "String",
    "",
    "auto",
    "Use this prop to set table-layout css property (e.g. 'auto' or 'fixed').",
    "",
  ],
];
