/* eslint-disable */
export default [
  [ "Props", "Type", "Required", "Default value", "Description" ],
  [
    "color",
    "String",
    "true",
    "",
    "Use this props to change the color of the button. Values can be 'default', 'primary',  'secondary', 'tertiary', 'success', 'warning', 'high', 'info', 'granite'",
  ],
  [
    "fill",
    "Boolean",
    "",
    "false",
    "Use this props to use fill button"
  ],
  [
    "ghost",
    "Boolean",
    "",
    "false",
    "Use this props to use ghost button"
  ],
  [
    "height",
    "[Number, String]",
    "",
    "32",
    "Use this props to change the height of the button",
  ],
  [
    "icon",
    "Boolean",
    "",
    "false",
    "Use this props to add icon in the button",
  ],
  [
    "outline",
    "Boolean",
    "",
    "false",
    "Use this props to use outline button",
  ],
  [
    "padding",
    "String",
    "",
    "0 calc(var(--spacing-unit) / 2)",
    "Use this props to custom padding of the button",
  ],
  [
    "radius",
    "Boolean",
    "",
    "false",
    "Use this props to use radius button",
  ],
  [
    "ripple",
    "Boolean",
    "",
    "false",
    "Use this props to use button with ripple effect",
  ],
  [
    "rounded",
    "Boolean",
    "",
    "false",
    "Use this props to use rounded button",
  ],
  [
    "size",
    "String",
    "",
    "15px",
    "Use this props to custom font-size of the button",
  ],
  [
    "square",
    "Boolean",
    "",
    "false",
    "Use this props to use square button",
  ],
  [
    "weight",
    "[Number, String]",
    "",
    "normal",
    "Use this props to change the font-weight of the button. Values can be 'light', 'normal' or 'bold'",
  ],
  [
    "width",
    "[Number, String]",
    "",
    "32",
    "Use this props to change the min-width of the button",
  ],
];
