import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    "Getting started": {
      text: "Learn how to quickly get started with our component library to build expressive, consistent UI at BIMData.",
      path: "getting-started",
      img: require("./web/assets/img/icon-getting_stated.svg"),
      children: [
        {
          title: "Designers",
          img: require("./web/assets/img/icon-designers.svg"),
          path: "designers",
          text: "Collection of tools and resources you need to start designing with the BIMData design system.",
          btn: "Get design kit",
        },
        {
          title: "Developpers",
          img: require("./web/assets/img/icon-developpers.svg"),
          path: "developpers",
          text: "How to use the BIMData design system in your projects.",
          btn: "Get dev kit",
        },
        {
          title: "InternalDoc",
          img: require("./web/assets/img/icon-doc.svg"),
          path: "internal-doc",
          text: "Documentation, if you want to add your own components",
          btn: "Getting started",
        },
      ],
    },
    "Guidelines & Utilities": {
      text: "How BIMData looks: guidelines for colors, spacing, typography, ...",
      img: require("./web/assets/img/icon-guidelines.svg"),
      path: "guidelines-utilities",
      children: [
        {
          title: "Utilities",
          path: "utilities",
          img: require("./web/assets/img/icon-utilities2.svg"),
          text: "Summary of all defined and usable classes and how use them.",
          btn: "View utilities",
        },
        {
          title: "Variables",
          path: "variables",
          img: require("./web/assets/img/icon-variables.svg"),
          text: "See all defines and usable BIMData variables and how use it.",
          btn: "View variables",
        },
        {
          title: "Colors",
          path: "colors",
          img: require("./web/assets/img/icon-colors.svg"),
          text: "BIMData uses a color palette to achieve clean interfaces.",
          btn: "View colors",
        },
        {
          title: "list",
          img: require("./web/assets/img/icon-list.svg"),
          path: "list",
          text: "Minimal layout container for displaying a group of items.",
          btn: "View list",
        },
        {
          title: "Markup & Style",
          img: require("./web/assets/img/icon-markup.svg"),
          path: "markup",
          text: "How to name your classes to respect the structure already in place.",
          btn: "View markup",
        },
        {
          title: "Spacing",
          img: require("./web/assets/img/icon-spacing.svg"),
          path: "spacing",
          text: "Adjust whitespace by applying spacing, margin, padding helpers.",
          btn: "View spacing",
        },
        {
          title: "Typography",
          img: require("./web/assets/img/icon-typo.svg"),
          path: "typography",
          text: "Indispensable for defining visual identity and organizing content.",
          btn: "View typography",
        },
      ],
    },
    Components: {
      text: "We developed a VueJS UI library that contains a set of components and demos for building interactive user interfaces.",
      img: require("./web/assets/img/icon-components.svg"),
      path: "components",
      children: [
        {
          title: "Buttons",
          img: require("./web/assets/img/icon-buttons.svg"),
          path: "buttons",
          text: "Buttons are used to trigger actions based on a user's interaction.",
          btn: "View buttons",
        },
        {
          title: "Cards",
          img: require("./web/assets/img/icon-card.svg"),
          path: "cards",
          text: "Cards are used to groups a related content.",
          btn: "View cards",
        },
        {
          title: "Carousel",
          img: require("./web/assets/img/icon-pagination.svg"),
          path: "carousel",
          text: "A generic carousel component.",
          btn: "View carousel",
        },
        {
          title: "Charts",
          img: require("./web/assets/img/icon-charts.svg"),
          path: "charts",
          text: "",
          btn: "View charts",
        },
        {
          title: "Checkbox",
          img: require("./web/assets/img/icon-checkbox.svg"),
          path: "checkbox",
          text: "Checkboxes are used to enables users to pick multiple options from a group.",
          btn: "View checkbox",
        },
        {
          title: "ColorSelector",
          img: require("./web/assets/img/icon-color_selector.svg"),
          path: "colorselector",
          text: "Color Selector component allows the user to pick from a set of predefined swatches colors.",
          btn: "View color selector",
        },
        {
          title: "DatePicker",
          img: require("./web/assets/img/icon-datepicker.svg"),
          path: "datepicker",
          text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          btn: "View DatePicker",
        },
        {
          title: "DropdownList",
          img: require("./web/assets/img/icon-dropdown.svg"),
          path: "dropdownlist",
          text: "DropdownList component shows a menu with an paginated list.",
          btn: "View dropdown list",
        },
        {
          title: "DropdownMenu",
          img: require("./web/assets/img/icon-dropdown.svg"),
          path: "dropdownmenu",
          text: "Dropdown component shows a simple menu.",
          btn: "View dropdown menu",
        },
        {
          title: "FileIcon",
          img: require("./web/assets/img/icon-fileicon.svg"),
          path: "fileicon",
          text: "FileIcon is used to provide file visual context.",
          btn: "View FileIcon",
        },
        {
          title: "Icons",
          img: require("./web/assets/img/icon-icons.svg"),
          path: "icons",
          text: "Icons are used to provide additional visual context.",
          btn: "View icons",
        },
        {
          title: "Illustrations",
          img: require("./web/assets/img/icon-illustration.svg"),
          path: "illustrations",
          text: "Illustrations are used to provide additional visual context.",
          btn: "View illustrations",
        },
        {
          title: "Input",
          img: require("./web/assets/img/icon-input.svg"),
          path: "input",
          text: "Inputs are used for enabled a user to interact and input data.",
          btn: "View input",
        },
        {
          title: "Loaders",
          img: require("./web/assets/img/icon-loader.svg"),
          path: "loaders",
          text: "Loaders are used to notify a user that data or page is being retrieved.",
          btn: "View loaders",
        },
        {
          title: "Menus",
          img: require("./web/assets/img/icon-menu.svg"),
          path: "menus",
          text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
          btn: "View menus",
        },
        {
          title: "ModelPreview",
          img: require("./web/assets/img/icon-doc.svg"),
          path: "model-preview",
          text: "Model preview component",
          btn: "View model preview",
        },
        {
          title: "Pagination",
          img: require("./web/assets/img/icon-pagination.svg"),
          path: "pagination",
          text: "Pagination is used to lets users navigate through large collections of items.",
          btn: "View pagination",
        },
        {
          title: "Radio",
          img: require("./web/assets/img/icon-radio.svg"),
          path: "radio",
          text: "Radio buttons enables a user to make a single selection from a group of options.",
          btn: "View radio",
        },
        {
          title: "ResponsiveGrid",
          img: require("./web/assets/img/icon-grid.svg"),
          path: "responsive-grid",
          text: "Display a list of item with a responsive layout",
          btn: "View responsive grid",
        },
        {
          title: "SafeZoneInline",
          img: require("./web/assets/img/icon-safe_zone_modal.svg"),
          path: "safe-zone-inline",
          text: "",
          btn: "View safe zone inline",
        },
        {
          title: "SafeZoneModal",
          img: require("./web/assets/img/icon-safe_zone_modal.svg"),
          path: "safe-zone-modal",
          text: "",
          btn: "View safe zone modal",
        },
        {
          title: "Search",
          img: require("./web/assets/img/icon-search.svg"),
          path: "search",
          text: "Search enables users to specify a word or a phrase to find relevant content.",
          btn: "View search",
        },
        {
          title: "Search Autocomplete",
          img: require("./web/assets/img/icon-search_autocomplete.svg"),
          path: "searchautocomplete",
          text: "Search autocomplete  ...",
          btn: "View search autocomplete",
        },
        {
          title: "Select",
          img: require("./web/assets/img/icon-select.svg"),
          path: "select",
          text: "Select (dropdown) is used to enabled a user to select a single item from a list of options.",
          btn: "View select",
        },
        {
          title: "Table",
          img: require("./web/assets/img/icon-table.svg"),
          path: "table",
          text: "Table is a component used for displaying your formatted content.",
          btn: "View table",
        },
        {
          title: "Tabs",
          img: require("./web/assets/img/icon-tabs.svg"),
          path: "tabs",
          text: "Tabs component provide a nice interface to switch between different views",
          btn: "View tabs",
        },
        {
          title: "Text",
          img: require("./web/assets/img/icon-text.svg"),
          path: "text",
          text: "Text",
          btn: "View text",
        },
        {
          title: "Textarea",
          img: require("./web/assets/img/icon-textarea.svg"),
          path: "textarea",
          text: "Textarea is used to add freeform longer text.",
          btn: "View textarea",
        },
        {
          title: "Textbox",
          img: require("./web/assets/img/icon-text.svg"),
          path: "textbox",
          text: "A text container to handle long text in small boxes.",
          btn: "View textbox",
        },
        {
          title: "Toggles",
          img: require("./web/assets/img/icon-toggle.svg"),
          path: "toggle",
          text: "Toggles are On/Off switches. They allow users to choose between two mutually exclusive options.",
          btn: "View toggle",
        },
        {
          title: "Tooltips",
          img: require("./web/assets/img/icon-tooltip.svg"),
          path: "tooltips",
          text: "Tooltips are used to show contextual information on hover.",
          btn: "View tooltips",
        },
      ],
    },
    "Smart Components": {
      text: "Smart components are components that are smart.",
      img: require("./web/assets/img/icon-smart-components.svg"),
      path: "smart-components",
      children: [
        {
          path: "file-manager",
          img: require("./web/assets/img/icon-list.svg"),
          title: "FileManager",
          text: "Navigate into a project file tree.",
          btn: "View file manager",
        },
      ],
    },
  },
});
