export default Object.freeze([
  {
    name: "High",
    hex: "#ff3d1e",
    rgb: "255, 61, 30",
    scss: "$color-high",
    css: "var(--color-high)",
    background: "bg-high",
    color: "color-high",
    fill: "fill-high",
    stroke: "stroke-high",
    textcolor: "#ffffff",
  },
  {
    name: "High 100",
    hex: "#ffedea",
    rgb: "255, 237, 234",
    scss: "$color-high-100",
    css: "var(--color-high-100)",
    background: "bg-high-100",
    color: "color-high-100",
    fill: "fill-high-100",
    stroke: "stroke-high-100",
    textcolor: "#2f374a",
  },
  {
    name: "High 400",
    hex: "#ff6851",
    rgb: "255, 104, 81",
    scss: "$color-high-400",
    css: "var(--color-high-400)",
    background: "bg-high-400",
    color: "color-high-400",
    fill: "fill-high-400",
    stroke: "stroke-high-400",
    textcolor: "#ffffff",
  },
  {
    name: "High 600",
    hex: "#ea1f00",
    rgb: "234, 31, 0",
    scss: "$color-high-600",
    css: "var(--color-high-600)",
    background: "bg-high-600",
    color: "color-high-600",
    fill: "fill-high-600",
    stroke: "stroke-high-600",
    textcolor: "#ffffff",
  },
]);
