export default Object.freeze([
  {
    name: "High",
    hex: "#ff3d1e",
    rgb: "255, 61, 30",
    scss: "$color-high",
    css: "var(--color-high)",
    background: "bg-high",
    color: "color-high",
    fill: "fill-high",
    stroke: "stroke-high",
    textcolor: "#ffffff",
  },
  {
    name: "High Lighter",
    hex: "#ffedea",
    rgb: "255, 237, 234",
    scss: "$color-high-lighter",
    css: "var(--color-high-lighter)",
    background: "bg-high-lighter",
    color: "color-high-lighter",
    fill: "fill-high-lighter",
    stroke: "stroke-high-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "High Light",
    hex: "#ff6851",
    rgb: "255, 104, 81",
    scss: "$color-high-light",
    css: "var(--color-high-light)",
    background: "bg-high-light",
    color: "color-high-light",
    fill: "fill-high-light",
    stroke: "stroke-high-light",
    textcolor: "#ffffff",
  },
  {
    name: "High Dark",
    hex: "#ea1f00",
    rgb: "234, 31, 0",
    scss: "$color-high-dark",
    css: "var(--color-high-dark)",
    background: "bg-high-dark",
    color: "color-high-dark",
    fill: "fill-high-dark",
    stroke: "stroke-high-dark",
    textcolor: "#ffffff",
  },
]);
