export default Object.freeze([
  {
    name: "Neutral",
    hex: "#205dbd",
    rgb: "32, 93, 189",
    css: "var(--color-neutral)",
    background: "bg-neutral",
    color: "color-neutral",
    fill: "fill-neutral",
    stroke: "stroke-neutral",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral Lighter",
    hex: "#f0f5ff",
    rgb: "240, 245, 255",
    css: "var(--color-neutral-lighter)",
    background: "bg-neutral-lighter",
    color: "color-neutral-lighter",
    fill: "fill-neutral-lighter",
    stroke: "stroke-neutral-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Neutral Light",
    hex: "#3375dd",
    rgb: "51, 117, 221",
    css: "var(--color-neutral-light)",
    background: "bg-neutral-light",
    color: "color-neutral-light",
    fill: "fill-neutral-light",
    stroke: "stroke-neutral-light",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral Dark",
    hex: "#194891",
    rgb: "25, 72, 145",
    css: "var(--color-neutral-dark)",
    background: "bg-neutral-dark",
    color: "color-neutral-dark",
    fill: "fill-neutral-dark",
    stroke: "stroke-neutral-dark",
    textcolor: "#ffffff",
  },
]);
