export default Object.freeze([
  {
    name: "Neutral",
    hex: "#205dbd",
    rgb: "32, 93, 189",
    css: "var(--color-neutral)",
    background: "bg-neutral",
    color: "color-neutral",
    fill: "fill-neutral",
    stroke: "stroke-neutral",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral 100",
    hex: "#f0f5ff",
    rgb: "240, 245, 255",
    css: "var(--color-neutral-100)",
    background: "bg-neutral-100",
    color: "color-neutral-100",
    fill: "fill-neutral-100",
    stroke: "stroke-neutral-100",
    textcolor: "#2f374a",
  },
  {
    name: "Neutral 400",
    hex: "#3375dd",
    rgb: "51, 117, 221",
    css: "var(--color-neutral-400)",
    background: "bg-neutral-400",
    color: "color-neutral-400",
    fill: "fill-neutral-400",
    stroke: "stroke-neutral-400",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral 600",
    hex: "#194891",
    rgb: "25, 72, 145",
    css: "var(--color-neutral-600)",
    background: "bg-neutral-600",
    color: "color-neutral-600",
    fill: "fill-neutral-600",
    stroke: "stroke-neutral-600",
    textcolor: "#ffffff",
  },
]);
