export default Object.freeze([
  {
    name: "Neutral",
    hex: "#205dbd",
    rgb: "32, 93, 189",
    scss: "$color-neutral",
    css: "var(--color-neutral)",
    background: "bg-neutral",
    color: "color-neutral",
    fill: "fill-neutral",
    stroke: "stroke-neutral",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral 100",
    hex: "#e2ebfa",
    rgb: "226, 235, 250",
    scss: "$color-neutral-100",
    css: "var(--color-neutral-100)",
    background: "bg-neutral-100",
    color: "color-neutral-100",
    fill: "fill-neutral-100",
    stroke: "stroke-neutral-100",
    textcolor: "#2f374a",
  },
  {
    name: "Neutral 400",
    hex: "#3374dd",
    rgb: "51, 116, 221",
    scss: "$color-neutral-400",
    css: "var(--color-neutral-400)",
    background: "bg-neutral-400",
    color: "color-neutral-400",
    fill: "fill-neutral-400",
    stroke: "stroke-neutral-400",
    textcolor: "#ffffff",
  },
  {
    name: "Neutral 600",
    hex: "#194791",
    rgb: "25, 71, 145",
    scss: "$color-neutral-600",
    css: "var(--color-neutral-600)",
    background: "bg-neutral-600",
    color: "color-neutral-600",
    fill: "fill-neutral-600",
    stroke: "stroke-neutral-600",
    textcolor: "#ffffff",
  },
]);
