export default Object.freeze([
  {
    name: "Primary",
    hex: "#2f374a",
    rgb: "47, 55, 74",
    css: "var(--color-primary)",
    background: "bg-primary",
    color: "color-primary",
    fill: "fill-primary",
    stroke: "stroke-primary",
    textcolor: "#ffffff",
  },
  {
    name: "Primary Lighter",
    hex: "#f8f9fa",
    rgb: "248, 249, 250",
    css: "var(--color-primary-lighter)",
    background: "bg-primary-lighter",
    color: "color-primary-lighter",
    fill: "fill-primary-lighter",
    stroke: "stroke-primary-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Primary Light",
    hex: "#434e69",
    rgb: "67, 78, 105",
    css: "var(--color-primary-light)",
    background: "bg-primary-light",
    color: "color-primary-light",
    fill: "fill-primary-light",
    stroke: "stroke-primary-light",
    textcolor: "#ffffff",
  },
  {
    name: "Primary Dark",
    hex: "#1b202b",
    rgb: "27, 32, 43",
    css: "var(--color-primary-dark)",
    background: "bg-primary-Dark",
    color: "color-primary-dark",
    fill: "fill-primary-Dark",
    stroke: "stroke-primary-Dark",
    textcolor: "#ffffff",
  },
]);
