export default Object.freeze([
  {
    name: "Primary",
    hex: "#2f374a",
    rgb: "47, 55, 74",
    scss: "$color-primary",
    css: "var(--color-primary)",
    background: "bg-primary",
    color: "color-primary",
    fill: "fill-primary",
    stroke: "stroke-primary",
    textcolor: "#ffffff",
  },
  {
    name: "Primary 100",
    hex: "#f8f9fa",
    rgb: "248, 249, 250",
    scss: "$color-primary-100",
    css: "var(--color-primary-100)",
    background: "bg-primary-100",
    color: "color-primary-100",
    fill: "fill-primary-100",
    stroke: "stroke-primary-100",
    textcolor: "#2f374a",
  },
  {
    name: "Primary 400",
    hex: "#434e69",
    rgb: "67, 78, 105",
    scss: "$color-primary-400",
    css: "var(--color-primary-400)",
    background: "bg-primary-400",
    color: "color-primary-400",
    fill: "fill-primary-400",
    stroke: "stroke-primary-400",
    textcolor: "#ffffff",
  },
  {
    name: "Primary 600",
    hex: "#1b202b",
    rgb: "27, 32, 43",
    scss: "$color-primary-600",
    css: "var(--color-primary-600)",
    background: "bg-primary-600",
    color: "color-primary-600",
    fill: "fill-primary-600",
    stroke: "stroke-primary-600",
    textcolor: "#ffffff",
  },
]);
