export default Object.freeze([
  {
    name: "Quaternary",
    hex: "#1C202C",
    rgb: "28, 32, 44",
    css: "var(--color-quaternary)",
    background: "bg-quaternary",
    color: "color-quaternary",
    fill: "fill-quaternary",
    stroke: "stroke-quaternary",
    textcolor: "#D1D8ED",
  },
  {
    name: "Quaternary Lighter",
    hex: "#D1D8ED",
    rgb: "209, 216, 237",
    css: "var(--color-quaternary-lighter)",
    background: "bg-quaternary-lighter",
    color: "color-quaternary-lighter",
    fill: "fill-quaternary-lighter",
    stroke: "stroke-quaternary-lighter",
    textcolor: "#242F4B",
  },
  {
    name: "Quaternary Light",
    hex: "#262B3C",
    rgb: "38, 43, 60",
    css: "var(--color-quaternary-light)",
    background: "bg-quaternary-light",
    color: "color-quaternary-light",
    fill: "fill-quaternary-light",
    stroke: "stroke-quaternary-light",
    textcolor: "#D1D8ED",
  },
  {
    name: "Quaternary Dark",
    hex: "#111622",
    rgb: "17, 22, 34",
    css: "var(--color-quaternary-dark)",
    background: "bg-quaternary-Dark",
    color: "color-quaternary-dark",
    fill: "fill-quaternary-Dark",
    stroke: "stroke-quaternary-Dark",
    textcolor: "#D1D8ED",
  },
  {
    name: "Quaternary Darker",
    hex: "#0C101B",
    rgb: "12, 16, 27",
    css: "var(--color-quaternary-darker)",
    background: "bg-quaternary-Darker",
    color: "color-quaternary-darker",
    fill: "fill-quaternary-Dark",
    stroke: "stroke-quaternary-Dark",
    textcolor: "#D1D8ED",
  },
]);
