export default Object.freeze([
  {
    name: "Quaternary",
    hex: "#242F4B",
    rgb: "36, 47, 75",
    css: "var(--color-quaternary)",
    background: "bg-quaternary",
    color: "color-quaternary",
    fill: "fill-quaternary",
    stroke: "stroke-quaternary",
    textcolor: "#ffffff",
  },
  {
    name: "Quaternary Lighter",
    hex: "#D1D8ED",
    rgb: "209, 216, 237",
    css: "var(--color-quaternary-lighter)",
    background: "bg-quaternary-lighter",
    color: "color-quaternary-lighter",
    fill: "fill-quaternary-lighter",
    stroke: "stroke-quaternary-lighter",
    textcolor: "#242F4B",
  },
  {
    name: "Quaternary Light",
    hex: "#272E42",
    rgb: "39, 46, 66",
    css: "var(--color-quaternary-light)",
    background: "bg-quaternary-light",
    color: "color-quaternary-light",
    fill: "fill-quaternary-light",
    stroke: "stroke-quaternary-light",
    textcolor: "#ffffff",
  },
  {
    name: "Quaternary Dark",
    hex: "#1F2535",
    rgb: "31, 37, 53",
    css: "var(--color-quaternary-dark)",
    background: "bg-quaternary-Dark",
    color: "color-quaternary-dark",
    fill: "fill-quaternary-Dark",
    stroke: "stroke-quaternary-Dark",
    textcolor: "#ffffff",
  },
]);
