export default Object.freeze([
  {
    name: "Secondary",
    hex: "#f9c72c",
    rgb: "249, 199, 44",
    scss: "$color-secondary",
    css: "var(--color-secondary)",
    background: "bg-secondary",
    color: "color-secondary",
    fill: "fill-secondary",
    stroke: "stroke-secondary",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary Lighter",
    hex: "#fffcf2",
    rgb: "255, 252, 242",
    scss: "$color-secondary-lighter",
    css: "var(--color-secondary-lighter)",
    background: "bg-secondary-lighter",
    color: "color-secondary-lighter",
    fill: "fill-secondary-lighter",
    stroke: "stroke-secondary-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary Light",
    hex: "#fad35e",
    rgb: "250, 211, 94",
    scss: "$color-secondary-light",
    css: "var(--color-secondary-light)",
    background: "bg-secondary-light",
    color: "color-secondary-light",
    fill: "fill-secondary-light",
    stroke: "stroke-secondary-light",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary Dark",
    hex: "#ebb607",
    rgb: "235, 182, 7",
    scss: "$color-secondary-dark",
    css: "var(--color-secondary-dark)",
    background: "bg-secondary-dark",
    color: "color-secondary-dark",
    fill: "fill-secondary-dark",
    stroke: "stroke-secondary-dark",
    textcolor: "#2f374a",
  },
]);
