export default Object.freeze([
  {
    name: "Secondary",
    hex: "#f9c72c",
    rgb: "249, 199, 44",
    scss: "$color-secondary",
    css: "var(--color-secondary)",
    background: "bg-secondary",
    color: "color-secondary",
    fill: "fill-secondary",
    stroke: "stroke-secondary",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary 100",
    hex: "#fffcf2",
    rgb: "255, 252, 242",
    scss: "$color-secondary-100",
    css: "var(--color-secondary-100)",
    background: "bg-secondary-100",
    color: "color-secondary-100",
    fill: "fill-secondary-100",
    stroke: "stroke-secondary-100",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary 400",
    hex: "#fad35e",
    rgb: "250, 211, 94",
    scss: "$color-secondary-400",
    css: "var(--color-secondary-400)",
    background: "bg-secondary-400",
    color: "color-secondary-400",
    fill: "fill-secondary-400",
    stroke: "stroke-secondary-400",
    textcolor: "#2f374a",
  },
  {
    name: "Secondary 600",
    hex: "#ebb607",
    rgb: "235, 182, 7",
    scss: "$color-secondary-600",
    css: "var(--color-secondary-600)",
    background: "bg-secondary-600",
    color: "color-secondary-600",
    fill: "fill-secondary-600",
    stroke: "stroke-secondary-600",
    textcolor: "#2f374a",
  },
]);
