export default Object.freeze([
  {
    name: "Silver",
    hex: "#d8d8d8",
    rgb: "216, 216, 216",
    css: "var(--color-silver)",
    background: "bg-silver",
    color: "color-silver",
    fill: "fill-silver",
    stroke: "stroke-silver",
    textcolor: "#2f374a",
  },
  {
    name: "Silver light",
    hex: "#f7f7f7",
    rgb: "247, 247, 247",
    css: "var(--color-silver-light)",
    background: "bg-silver-light",
    color: "color-silver-light",
    fill: "fill-silver-light",
    stroke: "stroke-silver-light",
    textcolor: "#2f374a",
  },
  {
    name: "Silver dark",
    hex: "#bdbdbd",
    rgb: "189, 189, 189",
    css: "var(--color-silver-dark)",
    background: "bg-silver-dark",
    color: "color-silver-dark",
    fill: "fill-silver-dark",
    stroke: "stroke-silver-dark",
    textcolor: "#2f374a",
  },
]);
