export default Object.freeze([
  {
    name: "Success",
    hex: "#00af50",
    rgb: "0, 175, 80",
    scss: "$color-success",
    css: "var(--color-success)",
    background: "bg-success",
    color: "color-success",
    fill: "fill-success",
    stroke: "stroke-success",
    textcolor: "#ffffff",
  },
  {
    name: "Success 100",
    hex: "#e2ffef",
    rgb: "226, 255, 239",
    scss: "$color-success-100",
    css: "var(--color-success-100)",
    background: "bg-success-100",
    color: "color-success-100",
    fill: "fill-success-100",
    stroke: "stroke-success-100",
    textcolor: "#2f374a",
  },
  {
    name: "Success 400",
    hex: "#00e266",
    rgb: "0, 226, 102",
    scss: "$color-success-400",
    css: "var(--color-success-400)",
    background: "bg-success-400",
    color: "color-success-400",
    fill: "fill-success-400",
    stroke: "stroke-success-400",
    textcolor: "#ffffff",
  },
  {
    name: "Success 600",
    hex: "#007c38",
    rgb: "0, 124, 56",
    scss: "$color-success-600",
    css: "var(--color-success-600)",
    background: "bg-success-600",
    color: "color-success-600",
    fill: "fill-success-600",
    stroke: "stroke-success-600",
    textcolor: "#ffffff",
  },
]);
