export default Object.freeze([
  {
    name: "Success",
    hex: "#00af50",
    rgb: "0, 175, 80",
    scss: "$color-success",
    css: "var(--color-success)",
    background: "bg-success",
    color: "color-success",
    fill: "fill-success",
    stroke: "stroke-success",
    textcolor: "#ffffff",
  },
  {
    name: "Success Lighter",
    hex: "#e2ffef",
    rgb: "226, 255, 239",
    scss: "$color-success-lighter",
    css: "var(--color-success-lighter)",
    background: "bg-success-lighter",
    color: "color-success-lighter",
    fill: "fill-success-lighter",
    stroke: "stroke-success-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Success Light",
    hex: "#00e266",
    rgb: "0, 226, 102",
    scss: "$color-success-light",
    css: "var(--color-success-light)",
    background: "bg-success-light",
    color: "color-success-light",
    fill: "fill-success-light",
    stroke: "stroke-success-light",
    textcolor: "#ffffff",
  },
  {
    name: "Success Dark",
    hex: "#007c38",
    rgb: "0, 124, 56",
    scss: "$color-success-dark",
    css: "var(--color-success-dark)",
    background: "bg-success-dark",
    color: "color-success-dark",
    fill: "fill-success-dark",
    stroke: "stroke-success-dark",
    textcolor: "#ffffff",
  },
]);
