export default Object.freeze([
  {
    name: "Tertiary Lightest",
    hex: "#f7f7f7",
    rgb: "247, 247, 247",
    scss: "$color-tertiary-lightest",
    css: "var(--color-tertiary-lightest)",
    background: "bg-tertiary-lightest",
    color: "color-tertiary-lightest",
    fill: "fill-tertiary-lightest",
    stroke: "stroke-tertiary-lightest",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary Lightest 600",
    hex: "#dddddd",
    rgb: "221, 221, 221",
    scss: "$color-tertiary-lightest-600",
    css: "var(--color-tertiary-lightest-600)",
    background: "bg-tertiary-lightest-600",
    color: "color-tertiary-lightest-600",
    fill: "fill-tertiary-lightest-600",
    stroke: "stroke-tertiary-lightest-600",
    textcolor: "#2f374a",
  },
]);
