export default Object.freeze([
  {
    name: "Tertiary",
    hex: "#d8d8d8",
    rgb: "216, 216, 216",
    scss: "$color-tertiary",
    css: "var(--color-tertiary)",
    background: "bg-tertiary",
    color: "color-tertiary",
    fill: "fill-tertiary",
    stroke: "stroke-tertiary",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary 100",
    hex: "#fafafa",
    rgb: "250, 250, 250",
    scss: "$color-tertiary-100",
    css: "var(--color-tertiary-100)",
    background: "bg-tertiary-100",
    color: "color-tertiary-100",
    fill: "fill-tertiary-100",
    stroke: "stroke-tertiary-100",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary 400",
    hex: "#e5e5e5",
    rgb: "229, 229, 229",
    scss: "$color-tertiary-400",
    css: "var(--color-tertiary-400)",
    background: "bg-tertiary-400",
    color: "color-tertiary-400",
    fill: "fill-tertiary-400",
    stroke: "stroke-tertiary-400",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary 600",
    hex: "#bebebe",
    rgb: "190, 190, 190",
    scss: "$color-tertiary-600",
    css: "var(--color-tertiary-600)",
    background: "bg-tertiary-600",
    color: "color-tertiary-600",
    fill: "fill-tertiary-600",
    stroke: "stroke-tertiary-600",
    textcolor: "#2f374a",
  },
]);
