export default Object.freeze([
  {
    name: "Tertiary Darkest",
    hex: "#606060",
    rgb: "96, 96, 96",
    scss: "$color-tertiary-darkest",
    css: "var(--color-tertiary-darkest)",
    background: "bg-tertiary-darkest",
    color: "color-tertiary-darkest",
    fill: "fill-tertiary-darkest",
    stroke: "stroke-tertiary-darkest",
    textcolor: "#ffffff",
  },
  {
    name: "Tertiary Darkest 100",
    hex: "#f7f7f7",
    rgb: "247, 247, 247",
    scss: "$color-tertiary-darkest-100",
    css: "var(--color-tertiary-darkest-100)",
    background: "bg-tertiary-darkest-100",
    color: "color-tertiary-darkest-100",
    fill: "fill-tertiary-darkest-100",
    stroke: "stroke-tertiary-darkest-100",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary Darkest 400",
    hex: "#797979",
    rgb: "121, 121, 121",
    scss: "$color-tertiary-darkest-400",
    css: "var(--color-tertiary-darkest-400)",
    background: "bg-tertiary-darkest-400",
    color: "color-tertiary-darkest-400",
    fill: "fill-tertiary-darkest-400",
    stroke: "stroke-tertiary-darkest-400",
    textcolor: "#ffffff",
  },
  {
    name: "Tertiary Darkest 600",
    hex: "#464646",
    rgb: "70, 70, 70",
    scss: "$color-tertiary-darkest-600",
    css: "var(--color-tertiary-darkest-600)",
    background: "bg-tertiary-darkest-600",
    color: "color-tertiary-darkest-600",
    fill: "fill-tertiary-darkest-600",
    stroke: "stroke-tertiary-darkest-600",
    textcolor: "#ffffff",
  },
]);
