export default Object.freeze([
  {
    name: "Tertiary",
    hex: "#59f4ff",
    rgb: "89, 244, 255",
    css: "var(--color-tertiary)",
    background: "bg-tertiary",
    color: "color-tertiary",
    fill: "fill-tertiary",
    stroke: "stroke-tertiary",
    textcolor: "#1C202C",
  },
  {
    name: "Tertiary Lighter",
    hex: "#F2FEFF",
    rgb: "242, 254, 255",
    css: "var(--color-tertiary-lighter)",
    background: "bg-tertiary-lighter",
    color: "color-tertiary-lighter",
    fill: "fill-tertiary-lighter",
    stroke: "stroke-tertiary-lighter",
    textcolor: "#1C202C",
  },
  {
    name: "Tertiary Light",
    hex: "#8CF7FF",
    rgb: "140, 247, 255",
    css: "var(--color-tertiary-light)",
    background: "bg-tertiary-light",
    color: "color-tertiary-light",
    fill: "fill-tertiary-light",
    stroke: "stroke-tertiary-light",
    textcolor: "#1C202C",
  },
  {
    name: "Tertiary Dark",
    hex: "#26F1FF",
    rgb: "38, 241, 255",
    css: "var(--color-tertiary-dark)",
    background: "bg-tertiary-dark",
    color: "color-tertiary-dark",
    fill: "fill-tertiary-dark",
    stroke: "stroke-tertiary-dark",
    textcolor: "#1C202C",
  },
  {
    name: "Tertiary Darker",
    hex: "#142630",
    rgb: "20, 38, 48",
    css: "var(--color-tertiary-darker)",
    background: "bg-tertiary-darker",
    color: "color-tertiary-darker",
    fill: "fill-tertiary-darker",
    stroke: "stroke-tertiary-darker",
    textcolor: "#D1D8ED",
  },
]);
