export default Object.freeze([
  {
    name: "Tertiary",
    hex: "#2672D2",
    rgb: "38, 114, 210",
    css: "var(--color-tertiary)",
    background: "bg-tertiary",
    color: "color-tertiary",
    fill: "fill-tertiary",
    stroke: "stroke-tertiary",
    textcolor: "#fff",
  },
  {
    name: "Tertiary Lighter",
    hex: "#f0f6fc",
    rgb: "240, 246, 252",
    css: "var(--color-tertiary-lighter)",
    background: "bg-tertiary-lighter",
    color: "color-tertiary-lighter",
    fill: "fill-tertiary-lighter",
    stroke: "stroke-tertiary-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary Light",
    hex: "#4c8ddf",
    rgb: "76, 141, 223",
    css: "var(--color-secondary-light)",
    background: "bg-secondary-light",
    color: "color-secondary-light",
    fill: "fill-secondary-light",
    stroke: "stroke-secondary-light",
    textcolor: "#fff",
  },
  {
    name: "Tertiary Dark",
    hex: "#1e5ba7",
    rgb: "30, 91, 167",
    css: "var(--color-secondary-dark)",
    background: "bg-secondary-dark",
    color: "color-secondary-dark",
    fill: "fill-secondary-dark",
    stroke: "stroke-secondary-dark",
    textcolor: "#fff",
  },
]);
