export default Object.freeze([
  {
    name: "Tertiary Dark",
    hex: "#7b7b7b",
    rgb: "123, 123, 123",
    scss: "$color-tertiary-dark",
    css: "var(--color-tertiary-dark)",
    background: "bg-tertiary-dark",
    color: "color-tertiary-dark",
    fill: "fill-tertiary-dark",
    stroke: "stroke-tertiary-dark",
    textcolor: "#ffffff",
  },
  {
    name: "Tertiary Dark 100",
    hex: "#eeeeee",
    rgb: "238, 238, 238",
    scss: "$color-tertiary-dark-100",
    css: "var(--color-tertiary-dark-100)",
    background: "bg-tertiary-dark-100",
    color: "color-tertiary-dark-100",
    fill: "fill-tertiary-dark-100",
    stroke: "stroke-tertiary-dark-100",
    textcolor: "#2f374a",
  },
  {
    name: "Tertiary Dark 400",
    hex: "#949494",
    rgb: "148, 148, 148",
    scss: "$color-tertiary-dark-400",
    css: "var(--color-tertiary-dark-400)",
    background: "bg-tertiary-dark-400",
    color: "color-tertiary-dark-400",
    fill: "fill-tertiary-dark-400",
    stroke: "stroke-tertiary-dark-400",
    textcolor: "#ffffff",
  },
  {
    name: "Tertiary Dark 600",
    hex: "#616161",
    rgb: "97, 97, 97",
    scss: "$color-tertiary-dark-600",
    css: "var(--color-tertiary-dark-600)",
    background: "bg-tertiary-dark-600",
    color: "color-tertiary-dark-600",
    fill: "fill-tertiary-dark-600",
    stroke: "stroke-tertiary-dark-600",
    textcolor: "#ffffff",
  },
]);
