export default Object.freeze([
  {
    name: "Warning",
    hex: "#ff9100",
    rgb: "255, 145, 0",
    scss: "$color-warning",
    css: "var(--color-warning)",
    background: "bg-warning",
    color: "color-warning",
    fill: "fill-warning",
    stroke: "stroke-warning",
    textcolor: "#ffffff",
  },
  {
    name: "Warning Lighter",
    hex: "#ffe9cc",
    rgb: "255, 233, 204",
    scss: "$color-warning-lighter",
    css: "var(--color-warning-lighter)",
    background: "bg-warning-lighter",
    color: "color-warning-lighter",
    fill: "fill-warning-lighter",
    stroke: "stroke-warning-lighter",
    textcolor: "#2f374a",
  },
  {
    name: "Warning Light",
    hex: "#ffa733",
    rgb: "255, 167, 51",
    scss: "$color-warning-light",
    css: "var(--color-warning-light)",
    background: "bg-warning-light",
    color: "color-warning-light",
    fill: "fill-warning-light",
    stroke: "stroke-warning-light",
    textcolor: "#ffffff",
  },
  {
    name: "Warning Dark",
    hex: "#cc7400",
    rgb: "204, 116, 0",
    scss: "$color-warning-dark",
    css: "var(--color-warning-dark)",
    background: "bg-warning-dark",
    color: "color-warning-dark",
    fill: "fill-warning-dark",
    stroke: "stroke-warning-dark",
    textcolor: "#ffffff",
  },
]);
