export default Object.freeze([
  {
    name: "Warning",
    hex: "#ff9100",
    rgb: "255, 145, 0",
    scss: "$color-warning",
    css: "var(--color-warning)",
    background: "bg-warning",
    color: "color-warning",
    fill: "fill-warning",
    stroke: "stroke-warning",
    textcolor: "#ffffff",
  },
  {
    name: "Warning 100",
    hex: "#ffe9cc",
    rgb: "255, 233, 204",
    scss: "$color-warning-100",
    css: "var(--color-warning-100)",
    background: "bg-warning-100",
    color: "color-warning-100",
    fill: "fill-warning-100",
    stroke: "stroke-warning-100",
    textcolor: "#2f374a",
  },
  {
    name: "Warning 400",
    hex: "#ffa733",
    rgb: "255, 167, 51",
    scss: "$color-warning-400",
    css: "var(--color-warning-400)",
    background: "bg-warning-400",
    color: "color-warning-400",
    fill: "fill-warning-400",
    stroke: "stroke-warning-400",
    textcolor: "#ffffff",
  },
  {
    name: "Warning 600",
    hex: "#cc7400",
    rgb: "204, 116, 0",
    scss: "$color-warning-600",
    css: "var(--color-warning-600)",
    background: "bg-warning-600",
    color: "color-warning-600",
    fill: "fill-warning-600",
    stroke: "stroke-warning-600",
    textcolor: "#ffffff",
  },
]);
