export default Object.freeze([
  {
    name: "High",
    hex: "#ff9100",
    rgb: "255, 145, 0",
    scss: "$color-high",
    css: "var(--color-high)",
    background: "bg-high",
    color: "color-high",
    fill: "fill-high",
    stroke: "stroke-high",
    textcolor: "#ffffff",
  },
  {
    name: "High 100",
    hex: "#ffe9cc",
    rgb: "255, 233, 204",
    scss: "$color-high-100",
    css: "var(--color-high-100)",
    background: "bg-high-100",
    color: "color-high-100",
    fill: "fill-high-100",
    stroke: "stroke-high-100",
    textcolor: "#2f374a",
  },
  {
    name: "High 400",
    hex: "#ffa733",
    rgb: "255, 167, 51",
    scss: "$color-high-400",
    css: "var(--color-high-400)",
    background: "bg-high-400",
    color: "color-high-400",
    fill: "fill-high-400",
    stroke: "stroke-high-400",
    textcolor: "#ffffff",
  },
  {
    name: "High 600",
    hex: "#cc7400",
    rgb: "204, 116, 0",
    scss: "$color-high-600",
    css: "var(--color-high-600)",
    background: "bg-high-600",
    color: "color-high-600",
    fill: "fill-high-600",
    stroke: "stroke-high-600",
    textcolor: "#ffffff",
  },
]);
