name: main

on: push

env:
  app: design

jobs:
  publish:
    runs-on: self-hosted
    if: contains('
          refs/heads/develop
          refs/heads/release
          refs/heads/master
          refs/heads/main'
        , github.ref)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
      - name: Setup npm
        run: npm install npm@latest -g
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
        run: npm run semantic-release
      - name: Checkout whit new commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
  build-and-push:
    runs-on: self-hosted
    if: contains('
          refs/heads/develop
          refs/heads/release
          refs/heads/master
          refs/heads/main'
        , github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v1
        with:
          branch: ${{ github.ref }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: etc/Dockerfile
          push: true
          pull: true
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ steps.tag.outputs.tag }}
  
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v1
        with:
          branch: ${{ github.ref }}
      - name: Deploy on ${{ steps.tag.outputs.tag }}
        uses: bimdata/actions/deployment@v1
        with:
          inventory: ${{ steps.tag.outputs.tag }}
          app: ${{ env.app }}
          vault-pass: ${{ secrets.ANSIBLE_VAULT_PASSWD }}


