name: main

on: push

env:
  app: design

jobs:
  publish:
    runs-on: [self-hosted, common]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup npm
        run: npm install npm@latest -g
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

  build-and-push:
    runs-on: [self-hosted, common]
    if: contains('
      refs/heads/develop
      refs/heads/master
      refs/heads/main'
      , github.ref)
    steps:
      - uses: actions/checkout@v3
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v2
        with:
          branch: ${{ github.ref }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: etc/Dockerfile
          push: true
          pull: true
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ env.tag }}

  deploy:
    runs-on: [self-hosted, common]
    needs: build-and-push
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v2
        with:
          branch: ${{ github.ref }}
      - name: Deploy on ${{ env.tag }}
        uses: bimdata/actions/deployment@v2
        with:
          inventory: ${{ env.tag }}
          app: ${{ env.app }}
          vault-pass: ${{ secrets.ANSIBLE_VAULT_PASSWD }}
