name: release/2.x

on:
  push:
    branches:
      - release/2.x

env:
  app: design

jobs:
  publish:
    runs-on: [self-hosted, common]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true
      - name: Setup npm
        run: npm install npm@latest -g
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

  build-and-push:
    runs-on: [self-hosted, common]
    needs: publish
    steps:
      - uses: actions/checkout@v5
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      # If branch is release/2.x, use prod as tag
      - if: ${{ startsWith(github.ref, 'refs/heads/release/2.x') }}
        name: Get docker tag
        run: echo "tag=prod" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: etc/Dockerfile
          push: true
          pull: true
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:v2-${{ env.tag }}

  deploy:
    runs-on: [self-hosted, common]
    needs: build-and-push
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      # We deploy on prod inventory, that why we set the tag to prod, yes the naming is confusing
      - name: Get docker tag
        run: |
          echo "tag=prod" >> $GITHUB_ENV
      - name: Deploy on ${{ env.tag }}
        uses: bimdata/actions/deployment@v3
        with:
          inventory: ${{ env.tag }}
          app: ${{ env.app }}
          vault-pass: ${{ secrets.ANSIBLE_VAULT_PASSWD }}
